# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

image: Visual Studio 2019

# environment variables
environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39-x64"

# scripts that run after cloning repository
install:
  # Ensure python scripts are from right version:
  - 'SET "PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%"'
  # Update pip/setuptools:
  - python -m pip install --upgrade setuptools pip
  # Install our package:
  - pip install .
  - pip install doit
  - doit install_test_deps

build: off

# to run your custom scripts instead of automatic tests
test_script:
  - doit test
